- name: disabling Redis YUM Modules
  ansible.builtin.shell:
    cmd: dnf module disable redis -y

- name: Configure Redis 6.2
  ansible.builtin.shell: dnf module enable redis:6 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed
    disable_gpg_check: yes

- name: Update Redis listen address from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127\.0\.0\.1'
      replace: '0.0.0.0'

#- name: Update Redis Listen address
#  ansible.builtin.replace:
#    path: "{{item}}"
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
#  loop:
#    - /etc/redis.conf
#    - /etc/redis/redis.conf

- name: Start Redis Service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
