- name: Install the latest version of nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Make sure nginx is running
  ansible.builtin.systemd:
    state: started
    name: nginx