- name: Copy Elastic YUM Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy Filebeat Configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart Filebeat Service
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: Update Kibana Config Port line
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: "server.port: 5601"

- name: Update Kibana Config IP line
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: localhost'
    line: "server.host: 0.0.0.0"

- name: Start Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
    enabled: yes