#LOG_FILE=/tmp/mysql
#source common.sh
#
#if [ -z "${ROBOSHOP_MYSQL_PASSWORD}" ]; then
#echo -e "\e[31m ROBOSHOP_MYSQL_PASSWORD env Variable is Needed\e[0m"
#exit 1
#fi
#
#echo "setting up  MySQL Repo file"
#curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo &>>$LOG_FILE
#statuscheck $?
#echo "Disable MY SQL Default Module to enable 5.7  MY SQL"
#dnf module disable mysql -y &>>$LOG_FILE
#statuscheck $?
#
#echo "Install MY SQL"
#yum install mysql-community-server -y &>>$LOG_FILE
#statuscheck $?
#
#echo "Start My SQL Service"
#systemctl enable mysqld &>>$LOG_FILE
#systemctl start mysqld &>>$LOG_FILE
#statuscheck $?
#
#DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}')
#
#echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${ROBOSHOP_MYSQL_PASSWORD}');
#FLUSH PRIVILEGES;" >/tmp/root-pass.sql
#
#echo "show databases;" |mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} &>>$LOG_FILE
#if [ $? -ne 0 ]; then
#echo "Change the default root password"
#mysql --connect-expired-password -uroot -p"${DEFAULT_PASSWORD}"  </tmp/root-pass.sql &>>$LOG_FILE
#statuscheck $?
#fi
#
#echo 'show plugins'| mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} 2>/dev/null | grep validate_password &>>$LOG_FILE
#if [ $? -eq 0 ]; then
#echo "Uninstall password validation plugin"
#echo "Uninstall plugin validate_password;" | mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} &>>LOG_FILE
#statuscheck $?
#fi
#echo "Download Schema "
#curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>LOG_FILE
#statuscheck $?
#
#echo "Extract schema"
#cd /tmp &>>LOG_FILE
#unzip -o mysql.zip &>>LOG_FILE
#statuscheck $?
#
#echo "Load Schema"
#cd mysql-main &>>LOG_FILE
#mysql -u root -p${ROBOSHOP_MYSQL_PASSWORD} <shipping.sql &>>LOG_FILE
##statuscheck $?

- name: Configure MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL Server Server and Python3 Dependency packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
    - mysql-community-devel
    - mysql-community-server
    - gcc
    - python36-devel

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Load the file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: out

- name: Install mysqlclient pip3
  ansible.builtin.pip:
    name: mysqlclient
    executable: pip3

- name: Check MySQL Credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ROBOSHOP_MYSQL_PASSWORD}}"
    filter: version
  ignore_errors: yes
  register: mysql_conn_status

- name: Copy SQL File to reset password
  ansible.builtin.template:
    src: reset-root-pass.sql
    dest: /tmp/reset-root-pass.sql
  when: mysql_conn_status is failed

- name: Change the root password
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{ out['content'] | b64decode | regex_findall('temporary password.*') |join(' ')  | split(' ') | last }}" </tmp/reset-root-pass.sql
  when: mysql_conn_status is failed

- name: Check MySQL Password Validate Plugin
  community.mysql.mysql_query:
    query: 'show plugins'
    login_user: root
    login_password: "{{ROBOSHOP_MYSQL_PASSWORD}}"
  ignore_errors: yes
  register: plugins_status

- name: Uninstall Password Validate Plugin
  community.mysql.mysql_query:
    query: 'uninstall plugin validate_password;'
    login_user: root
    login_password: "{{ROBOSHOP_MYSQL_PASSWORD}}"
  when: plugins_status | regex_findall('validate_password') | length > 0

